---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node4-sa
  namespace: besu
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: node4-key-read-role
  namespace: besu
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: [ besu-node4-key ]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: node4-rb
  namespace: besu
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: node4-key-read-role
subjects:
- kind: ServiceAccount
  name: node4-sa
  namespace: besu
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: node4
  labels:
    app: node4
  namespace: besu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node4
  serviceName: besu-node4
  template:
    metadata:
      labels:
        app: node4
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9545"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: node4-sa
      containers:
        - name: node4
          image: hyperledger/besu:24.3
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 1024Mi
            limits:
              cpu: 500m
              memory: 2048Mi
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODE1_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: besu-node1-key
                  key: publicKey
          volumeMounts:
            - name: key
              mountPath: /secrets
              readOnly: true
            - name: genesis-config
              mountPath: /etc/genesis
              readOnly: true
            - name: config-toml
              mountPath: /etc/besu
              readOnly: true
            - name: data
              mountPath: /data
          ports:
            - containerPort: 8545
              name: json-rpc
              protocol: TCP
            - containerPort: 8546
              name: ws
              protocol: TCP
            - containerPort: 8547
              name: graphql
              protocol: TCP
            - containerPort: 30303
              name: rlpx
              protocol: TCP
            - containerPort: 30303
              name: discovery
              protocol: UDP
          command:
            - /bin/sh
            - -c
          args:
            - |
              exec /opt/besu/bin/besu \
                --node-private-key-file=/secrets/key \
                --config-file=/etc/besu/config.toml \
                --Xdns-enabled=true --Xdns-update-enabled=true --Xnat-kube-service-name=besu-node4 \
                --bootnodes=enode://${NODE1_PUBLIC_KEY}@node1-0.besu-node1.besu.svc.cluster.local:30303
      volumes:
        - name: key
          secret:
            secretName: besu-node4-key
        - name: genesis-config
          configMap:
            name: besu-genesis-configmap
        - name: config-toml
          configMap:
            name: besu-config-toml-configmap
        - name: data
          persistentVolumeClaim:
            claimName: node1-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node4-pvc
  namespace: besu
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi